export const DSA_TAGS = [
  "Array",
  "String",
  "Hash Table",
  "Dynamic Programming",
  "Tree",
  "Graph",
  "Linked List",
  "Stack",
  "Queue",
  "Binary Search",
  "Recursion",
  "Two Pointers",
  "Sliding Window",
  "Greedy",
  "Backtracking",
  "Heap / Priority Queue",
  "Math",
  "Bit Manipulation",
  "Prefix Sum",
  "Sorting",
  "Depth First Search",
  "Breadth First Search",
  "Union Find",
  "Trie",
  "Matrix",
];